# ownCloud with MariaDB
#
# Access via "http://localhost:8080" (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial ownCloud setup, select "Storage & database" --> "Configure the database" --> "MySQL/MariaDB"
# Database user: root
# Database password: my-database-password
# Database name: pick any name
# Database host: replace "localhost" with owncloud_db 

ampache:
  image: ampache/ampache
  container_name: arify_ampache
  links: 
    - arify_owncloud
  ports: 
    - 6060:80
  volumes:
    - "/home/ariel/arify/data:/media:ro"
  
arify_owncloud:
  image: owncloud:9
  container_name: arify_owncloud
  links:
    - arify_db
  ports:
    - 7070:80
  volumes:
    - "/home/ariel/arify/data:/var/www/html/data"

arify_db:
  image: mariadb
  container_name: arify_db
  environment:
    MYSQL_ROOT_PASSWORD: letsenjoythisgreatmusic!!!
