version: '2'

services:

  ampache:
    image: ampache/ampache
    container_name: arify_ampache
    restart: always
    links: 
      - arify_owncloud
    ports: 
      - ${AMPACHE_PORT}:80
    volumes:
      - "${OWNCLOUD_DATA_DIRECTORY}:/media:ro"


  arify_owncloud:
    image: owncloud:9
    container_name: arify_owncloud
    restart: always
    links:
      - arify_db
    ports:
      - ${OWNCLOUD_PORT}:80
    volumes:
      - "${OWNCLOUD_DATA_DIRECTORY}:/var/www/html/data"

  arify_db:
    image: mariadb
    container_name: arify_db
    restart: always
    volumes: 
      - "${DATABASE_CONFIG_DIRECTORY}:/var/lib"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
